---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-eks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-projects
  source:
    repoURL: https://github.com/mvtech88/crossplane-argocd-eks.git
    targetRevision: HEAD
    path: crossplane-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 4
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

