apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-helm
  annotations:
    argocd.argoproj.io/sync-wave: "60"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: crossplane/provider-helm:v0.9.0
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-provider-1
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "70"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "60"]
      restartPolicy: Never
