apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: eks-infra
spec:
  crossplane:
    version: ">=v1.4.1"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.23.0"
    - provider: crossplane/provider-helm
      version: ">=v0.9.0"
